### ISSUE TITLE
uri.indexOf is not a function

### ISSUE THREAD

**Issue by diegohaz** [Mockgoose/Mockgoose#4]
I'm trying to use Mockgoose with [AVA](https://github.com/avajs/ava), but I'm getting this error when trying to test 2 or more files in parallel:

```
failed with "uri.indexOf is not a function"
      checkReplicaSetInUri (/Users/diegohaz/Projects/cblhub-test/node_modules/mongoose/lib/index.js:115:30)
    Mongoose.connect (/Users/diegohaz/Projects/cblhub-test/node_modules/mongoose/lib/index.js:238:40)
    Mongoose.mongoose.connect (/Users/diegohaz/Projects/cblhub-test/node_modules/mockgoose/Mockgoose.js:82:33)
    _callee$ (auth.test.js:16:18)
    tryCatch (/Users/diegohaz/Projects/cblhub-test/node_modules/regenerator-runtime/runtime.js:62:40)
    GeneratorFunctionPrototype.invoke [as _invoke] (/Users/diegohaz/Projects/cblhub-test/node_modules/regenerator-runtime/runtime.js:336:22)
    GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/diegohaz/Projects/cblhub-test/node_modules/regenerator-runtime/runtime.js:95:21)
```

**Comment by diegohaz** [comment]
This bug was introduced in #2 on [Mockgoose.js#L144](https://github.com/Mockgoose/Mockgoose/blob/master/Mockgoose.js#L144).

I didn't understand why `start_server_callback` was passed to `mongod.start_server`. An anonymous function should be enough to fix #1. 

It's also confusing how `mongod.start_server` works. It appears to be asynchronous and in its [documentation](https://github.com/winfinit/mongodb-prebuilt#start_serveropts-callback) it says that the callback is executed both on success and failure, but it's only executed on failure with a number argument (which causes this bug `48.indexOf is not a function`).
